name: mcdr-atlas
channels:
- conda-forge
- default
dependencies:
- cartopy
- cmocean
- dask
- distributed
- dask-jobqueue
- esmpy
- ffmpeg
- holoviews
- ipywidgets
- jupyter-book
- jupyter_client
- jupyterlab
- matplotlib
- nb_conda_kernels
- nbformat
- nbterm
- netCDF4
- numpy
- PyCO2SYS
- pandas
- pop-tools
- scipy
- seawater
- xarray
- xesmf
- xgcm
- zarr
